CREATE TABLE assistant_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    role VARCHAR(16) NOT NULL,
    content TEXT NOT NULL,
    source VARCHAR(32),
    status VARCHAR(32),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_assistant_message_user
        FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE,
    CONSTRAINT ck_assistant_message_role
        CHECK (role IN ('USER', 'ASSISTANT')),
    CONSTRAINT ck_assistant_message_shape
        CHECK (
            (role = 'USER' AND source IS NOT NULL AND status IS NULL)
            OR
            (role = 'ASSISTANT' AND source IS NULL AND status IS NOT NULL)
        )
);

CREATE INDEX idx_assistant_message_user_id_id
    ON assistant_message (user_id, id);
